state.x77
str(state.x77)
states = as.data.frame(state.x77[,c('Murder','Population','Illiteracy','Income','Frost')])
str(states)
fit1 = lm(Murder~Population+Illiteracy+Income+Frost,data=states)
fit2 = lm(Murder~Population+Illiteracy,data=states)
summary(fit1)
summary(fit2)
anova(fit2,fit1)
s1 = as.data.frame(state.x77)
str(s1)
f1 = lm(Murder~.-Murder,data=s1)
summary(f1)
AIC(fit1,fit2)
