library(dplyr)
library(nycflights13)
data("flights")
f = flights
str(f)
dplyr::tbl_df(iris)
tbl_df(iris) %>% print(n=Inf)
tbl_df(iris) %>% print(width=Inf)
tbl_df(iris) %>% as.data.frame(iris)
glimpse(iris)

mtcars['mpg']
mtcars %>% select(vs,mpg)
select(mtcars,mpg,vs)
mtcars %>% group_by(cyl) %>% summarise(avg=mean(wt),m1 = mean(hp)) %>% arrange(avg)
mtcars %>% group_by(cyl) %>% summarise(avg1=mean(wt),m2 = mean(hp)) %>% arrange(avg1,desc(m2))
filter(mtcars,mpg>23)
mtcars %>% filter(mpg>23)
filter(mtcars,cyl > 4)
mtcars %>% filter(cyl > 6)
distinct(mtcars)

sample_frac(mtcars,0.2,replace=T)
sample_n(mtcars,2,replace=T)
slice(mtcars,1:4)
top_n(mtcars,2,mpg)
select(mtcars,contains('wt'))
select(mtcars,contains('a'))
summarise_all(iris,funs(mean))
mtcars %>% group_by(cyl,am) %>% summarise_all(mean)
mutate(mtcars,mpg2 = 2*mpg)
mutate_each(mtcars,funs(min_rank))
df = data.frame(marks=c(1,2,3,7,1))
cbind(df,dplyr::mutate_each(df,funs(min_rank)))
a = data.frame(x1=c('A','B','C'),x2=c(1,2,3))
b = data.frame(x1=c('A','B','D'),x3=c('T','F','T'))
a
b
dplyr::left_join(a,b,by='x1')
