library(arules)
library(arulesViz)
library(datasets)
data("Groceries")
itemFrequencyPlot(Groceries,topN=20,type='absolute')
inspect(Groceries[1:5])
LIST(Groceries[1:5])
fi <- eclat(Groceries,parameter = list(supp=0.07,maxlen=15))
fi
inspect(fi)
fi2 = eclat(Groceries,parameter = list(supp=0.02,maxlen=25))
fi2
inspect(fi2)
rules = apriori(Groceries,parameter = list(supp=0.001,conf=0.5))
inspect(rules)
inspect(rules[1:5])
rules1 = sort(rules,by='lift',decreasing = T)
rules1
inspect(rules1[1:5])
rules2 = apriori(Groceries,parameter = list(supp=0.001,conf=0.5,maxlen=5))
inspect(rules2[1:5])
rules = apriori(Groceries,parameter = list(supp=0.001,conf=0.08),appearance = list(default='lhs',rhs='whole milk')
,control = list(verbose=F))
inspect(rules[1:5])
rules5 = apriori(Groceries,parameter = list(supp=0.001,conf=0.08),appearance = list(default='rhs',lhs='whole milk')
                ,control = list(verbose=F))
inspect(rules5[1:20])
plot(rules[1:20],method='graph',interactive=T,shading=NA)
