library(forecast)
library(tseries)
df1 = read.csv('./data/Sales.csv',na.strings = c(''))
str(df1)
TSdata=df1
summary(TSdata)
colSums(is.na(TSdata))
names(TSdata)[c(1:2)]=c('Data','Sales')
TSdata=ts(TSdata[,2],start=c(2003,1),frequency = 12)
start(TSdata)
frequency(TSdata)
StructTS(TSdata)
str(TSdata)
class(TSdata)
plot(TSdata)
abline(reg=lm(TSdata~time(TSdata)))
cycle(TSdata)
plot(log10(TSdata))
plot(diff(TSdata,differences = 1))
plot(diff(log10(TSdata),differences = 1))
LDTSdata=diff(log10(TSdata),differences = 1)
require(forecast)
adf.test(LDTSdata,alternative = 'stationary')
kpss.test(LDTSdata)
adf.test(TSdata,alternative = 'stationary')
par(mfrow=c(1,2))
pacf(LDTSdata)
acf(LDTSdata)
afit=arima((log10(TSdata)),c(1,1,0))
summary(afit)
afit1=auto.arima(log10(TSdata),approximation = TRUE,trace = TRUE)
summary(afit1)
pred = predict(afit1,n.ahead = 36)
pred[1:5]
par(mfrow=c(1,1))
plot(TSdata)
lines(10^(pred$pred),col='red')
lines(10^(pred$pred+2*pred$se),col='blue')
lines(10^(pred$pred-2*pred$se),col='grey')
