f1 = faithful
str(f1)
mean(f1$eruptions)
median(f1$eruptions)
quantile(f1$eruptions)
quantile(f1$eruptions,c(.32,.57,.98))
range(f1$eruptions)
attach(f1)
IQR(eruptions)
sd(eruptions)
(sd(eruptions))^2
var(eruptions)
library(fBasics)
skewness(eruptions)
kurtosis(eruptions)
stem(eruptions)
plot(eruptions,waiting)
abline(lm(waiting~eruptions), col="red")
hist(eruptions)
boxplot(eruptions)
is = InsectSprays
boxplot(is)
boxplot(is$count~is$spray)
cov(eruptions,waiting)
cor(eruptions,waiting)
